# Generated by Django 2.1.5 on 2019-12-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_image',
        ),
    ]
